CREATE TABLE "SNOW_PRACTS"."PRACTICE_SCH"."Customer_2" ( C_CUSTOMER_SK NUMBER(38, 0) , C_CUSTOMER_ID VARCHAR , C_CURRENT_CDEMO_SK VARCHAR , C_CURRENT_HDEMO_SK VARCHAR , C_CURRENT_ADDR_SK NUMBER(38, 0) , C_FIRST_SHIPTO_DATE_SK VARCHAR , C_FIRST_SALES_DATE_SK VARCHAR , C_SALUTATION VARCHAR , C_FIRST_NAME VARCHAR , C_LAST_NAME VARCHAR , C_PREFERRED_CUST_FLAG VARCHAR , C_BIRTH_DAY VARCHAR , C_BIRTH_MONTH VARCHAR , C_BIRTH_YEAR VARCHAR , C_BIRTH_COUNTRY VARCHAR , C_LOGIN VARCHAR , C_EMAIL_ADDRESS VARCHAR , C_LAST_REVIEW_DATE VARCHAR ); 

CREATE TEMP FILE FORMAT "SNOW_PRACTS"."PRACTICE_SCH"."temp_file_format_2025-07-25T12:04:21.229Z"
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "SNOW_PRACTS"."PRACTICE_SCH"."Customer_2" 
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
	FROM '@"SNOW_PRACTS"."PRACTICE_SCH"."__snowflake_temp_import_files__"') 
FILES = ('2025-07-25T12:03:30.613Z/Customer_quote.csv') 
FILE_FORMAT = '"SNOW_PRACTS"."PRACTICE_SCH"."temp_file_format_2025-07-25T12:04:21.229Z"' 
ON_ERROR=ABORT_STATEMENT 
-- For more details, see: https://docs.snowflake.com/en/sql-reference/sql/copy-into-table